### ISSUE TITLE
@ManyToMany relations?

### ISSUE THREAD

**Issue by es-lynn** [SoftwareBrothers/adminjs-typeorm#28]
Hi, checked the documentation but there was no info about it. Wondering if there is any support for `@ManyToMany` relations at the moment?

**Comment by dziraf** [comment]
We don't plan on adding out-of-the-box support for M:M relations currently. We would need to think of proper UI solutions for this since we definitely wouldn't like to e. g. fetch hundreds of related records at once.

However, current AdminJS ecosystem allows to create hooks and custom components which should let you achieve M:M support in your own customized way
